### ISSUE TITLE
Smooth lighting is disabled on mod blocks

### ISSUE THREAD

**Issue by SimonMeskens** [IntelligenceModding/LaboratoryBlocks#1]
![image](https://github.com/DoomedArtemis/LaboratoryBlocks/assets/4284735/ad3bc6d9-4017-4fbe-b7bc-572cbbba6188)

The walls are laboratory blocks and the most clear. If you look at the ceiling or the gray-brown concrete floor, they are lit smoothly, the blocks from LaboratoryBlocks are not.

**Comment by DoomedArtemis** [comment]
I tested it with the newest 1.20 version, together with fusion. Maybe it was a CTM problem, or just a conflict with another mod, like Sodium or Optifine.
If you still want, you could test it on 0.3.2.2r, together with Fusion. If it then still isn't working, it would be great if you could open a new issue.
