### ISSUE TITLE
[BUG] Recipe conflict with vanilla by overriding

### ISSUE THREAD

**Issue by DevDyna** [IntelligenceModding/LaboratoryBlocks#2]
I have found that it can override the recipe of redstone dust from redstone block due same file name
from mod : `data/minecraft/recipes/redstone.json` 
from vanilla : `data/minecraft/recipes/redstone.json`

**Comment by DoomedArtemis** [comment]
Hey there, sorry for the late answer. I'll quickly fix that in the coming days.

**Comment by DoomedArtemis** [comment]
I'll upload the fixed version as soon as possible.
